#!/bin/bash

JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '.js\|.jsx\|.scss\|.css' | tr '\n' ' ')
[ -z "$JS_FILES" ] && exit 0

# Prettify all staged *.js(x), *.(s)css files
echo "$JS_FILES" | xargs ./web/node_modules/.bin/prettier --write

# Readd the modified files to staging
echo "$JS_FILES" | xargs git add

exit 0
